name: github-actions-demo
on:
    push:
        branches:
        - main
jobs:
    wersja_pythona:
    runs-on: windows-latest
    steps:
      - name: Wyswietlanie wersji pythona
        run: python --version
    testuj_przez_pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint
        run: |
          pylint app.py