name: github-actions-demo
on:
    push:
        branches:
        - main
jobs:
    wersja_pythona:
    runs-on: windows-latest
    steps:
      - name: Wyswietlanie wersji pythona
        run: python --version
    testuj_przez_pylint:
        runs-on: windows-latest
        steps:
          - name: sprawdz_kod
            uses: actions/checkout@v2

          - name: Ustaw_python
            uses: actions/setup-python@v2
            with:
              python-version: 3.x

          - name: Zainstaluj
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Uruchom_Pylint
            run: |
              pylint app.py